odoo/documentation

accounting/receivables/customer_invoices/overview.rst
Based on https://docs.google.com/document/d/1JjDhhjsChRxgAFjfViSWxaw66a21breSDoFlk7LfeQs/edit#
=> [ADD] accounting: overview of the invoice process

accounting/receivables/customer_invoices/payment_terms.rst
based on https://docs.google.com/document/d/15O-gVohiyhEObrM81B1iB5qFFuwjderK357r2zAdrJY/edit#heading=h.rnc4w7jho1pm
=> [ADD] accounting: using payment terms

crm/overview.rst, crm/overview/main_concepts.rst, crm/overview/main_concepts/terminologies.rst
https://docs.google.com/document/d/1MIVVlzP7icYtgZtTzXi3lc_GV5sbwSFYeZyILdpdzJg/edit
=> [ADD] crm: Odoo CRM Terminologies

.tx/config, Makefile, conf.py, locale/sources/accounting.pot, locale/sources/applications.pot, locale/sources/crm.pot, locale/sources/expenses.pot, locale/sources/index.pot, locale/sources/inventory.pot, locale/sources/point_of_sale.pot, locale/sources/purchase.pot, locale/sources/recruitment.pot
New command make i18nhtml to add parameter LANG=...
e.g. `make LANG=fr i18nhtml`
Problem: need to make one make per language.
=> Enable translations

project/overview/main_concepts/introduction.rst
https://www.youtube.com/watch?v=PWKez0gn6Ts
=> [ADD] project: Introduction to Odoo project

accounting/overview/main_concepts.rst, accounting/overview/main_concepts/intro.rst, project.rst, project/application.rst, project/application/intro.rst, sales/overview/main_concepts/introduction.rst, sales/overview/main_concepts/invoicing.rst
=> [ADD] sale: From quotation to sales order

inventory/routes/costing.rst, project.rst, project/advanced.rst, project/configuration.rst, project/overview/main_concepts.rst, project/planning.rst, project/reporting.rst, purchase/overview.rst, purchase/overview/concepts.rst, purchase/overview/start.rst, purchase/purchases/master.rst, purchase/purchases/rfq.rst, purchase/replenishment/flows.rst, purchase/replenishment/trouble_shooting.rst, sales.rst, sales/advanced.rst, sales/invoicing.rst, sales/invoicing/misc.rst, sales/invoicing/products.rst, sales/invoicing/services.rst, sales/overview.rst, sales/overview/main_concepts.rst, sales/overview/process.rst, sales/products_prices.rst, sales/products_prices/prices.rst, sales/products_prices/products.rst, sales/quotation.rst, sales/quotation/online.rst, sales/quotation/setup.rst, sales/reporting.rst
=> [IMP] Remove empty pages from TOCs

locale/sources/point_of_sale.pot, point_of_sale/belgian_fdm/setup.rst
Specifiy explicitely that the on-premise module is for Enterprise customers
and that bying a POSbox is not enough.
=> [IMP] pos: certification and on-premise

conf.py, legal.rst, legal/terms.rst, legal/terms/i18n/terms_of_sale_fr.rst, legal/terms/i18n/terms_of_sale_tex_fr.rst, legal/terms/terms_of_sale.rst, legal/terms/terms_of_sale_tex.rst
Task: https://www.odoo.com/web?debug=#id=31917&view_type=form&model=project.task&action=327&menu_id=4720
- rst web page
- latexpdf files & config
=> [ADD] legal: terms of sales

_extensions/odoo/sub-menu_list.html, crm/leads/manage/automatic_assignation.rst, crm/overview/main_concepts/terminologies.rst, db_management/db_premise.rst, helpdesk/helpdesk.rst, legal/others/cla.rst, locale/sources/crm.pot, locale/sources/db_management.pot, locale/sources/helpdesk.pot, locale/sources/point_of_sale.pot, locale/sources/purchase.pot, point_of_sale/overview/setup.rst, purchase/purchases/tender/manage_multiple_offers.rst
Description of the issue/feature this PR addresses: This PR updates the urls to v11.
Current behavior before PR: Some urls are deprecated.
Desired behavior after PR is merged: All the urls are v11.
=> [11.0][FIX] update urls to v11

accounting/others/adviser/budget.rst, accounting/others/analytic/purchases_expenses.rst, purchase/purchases/rfq/analyze.rst, purchase/purchases/rfq/cancel.rst, purchase/purchases/rfq/create.rst, purchase/purchases/rfq/reception.rst, purchase/purchases/tender/manage_multiple_offers.rst, purchase/purchases/tender/partial_purchase.rst, purchase/replenishment/flows/purchase_triggering.rst
=> [FIX] purchase: remove reference to removed page

sales/products_prices/prices/B2B_B2C.rst
price included => tax included
price excluded => tax excluded
=> [9.0] FIX price included => tax included and so on

general/unsplash/unsplash_access_key.rst, general/unsplash/unsplash_application_id.rst
Countinuity of 7d16eb9619f41c20bd591ff10fe249a33d31d520
=> [FIX] unsplash: fine-tune the doc to fit exactly last changes

accounting/localizations/mexico.rst
Based on this change:
https://github.com/odoo/enterprise/pull/2993
=> [IMP] mexico.rst: Completed documentation about the payment term

db_management/db_premise.rst
If it is not you who reviews & merge the user doc, can you redirect me to the right person?
=> [IMP] db_management: ports/domains for the ping

_extensions/odoo/__init__.py, _extensions/odoo/layout.html, _extensions/odoo/translator.py
Cherry-pick of odoo/odoo@2b28dd89b8b767611
Todo: test and stuff
=> [FIX] odoo: compatibility sphinx2

accounting/others/taxes/application.rst
Fixes two grammatical mistakes
=> [FIX] Correct grammatical errors

odoo_sh/getting_started/branches.rst, odoo_sh/getting_started/online-editor.rst
=> Explain overlay fs features

accounting/localizations/mexico.rst
=> WIP: 2019 l10n_mx update

inventory/settings/products/uom.rst
Inventory Control was renamed to Master Data in https://github.com/odoo/odoo/commit/5a9667245365734ddcd8b101f36d4c15e72ad093
Info @wt-io-it
=> replace Inventory Control by Master Data

website/publish/domain_name.rst
update SSL doc for the saas
https://www.odoo.com/web?debug#id=2066466&model=project.task&view_type=form&menu_id=5200
=> Update SSL doc for the saas

odoo_sh/advanced/frequent_technical_questions.rst
opw-[2058254](https://www.odoo.com/web?debug#id=2058254&model=project.task&view_type=form&menu_id=5200)
=> [IMP] odoo_sh: recurring question about crons

Makefile, accounting/payables/supplier_bills/manage.rst, crm/acquire_leads/generate_from_website.rst, sales/send_quotations/deadline.rst
I made edits to several of the documentation files to improve the grammar and punctuation on them. Feel free to review the changes and suggest edits.
=> generate_from_website grammar check

general/unsplash/unsplash_access_key.rst
I rearranged some of the words in this documentation and made a few other tweaks to the wording.
=> unsplash_access_key grammar check

general/base_import/import_faq.rst
Fix first paragraph of date format FAQ to improve clarity.
Thanks to @osg for the help.
=> Rewrite date format FAQ entry

sales/products_prices/prices/pricing.rst
Add a note to show where each sales settings option is explained.  And minor edits for clarity.
=> show where each sales settings is explained

_extensions/odoo/sub-menu_list.html
=> [ADD] searchbar

_extensions/odoo/layout.html, conf.py
Task id: 2121586
Pad: https://pad.odoo.com/p/r.83090664d0c2a9f20ff54edc93e80d70
=> [IMP] SEO stuff

inventory/management/products/usage.rst
More details on how to separate a picking into more than one package.
=> More details on picking with multiple packages

inventory/management/reporting/inventory_valuation_config.rst
The documentation page has been cleaned to avoid repeating some information. 
Some information has also been changed to be up to date with new version.
=> [IMP] Inventory valuation: update documentation

accounting/others/taxes/taxcloud.rst
to merge once module is validated + backport 11/12
=> [IMP] taxcloud: coupon nightmare

marketing_automation/advanced/understanding_metrics.rst
just needs to be merged, please!!
=> [IMP] marketing automation: delete of a word

accounting/bank/setup/create_bank_account.rst, accounting/bank/setup/manage_cash_register.rst, accounting/payables/pay/check.rst, inventory/routes/concepts/procurement_rule.rst, inventory/routes/concepts/push_rule.rst, purchase/purchases/rfq/create.rst
*: accounting, inventory, purchase
@mart-e , would you also remove the code related to the actions?
Cheers :)
Jon
=> [REM] *: remove all demo.action buttons from the user documentation

general/developer_mode/activate.rst
To be merged. I just changed the place where the 'tip' message was.
=> [IMP] general: quick adjustment on developer mode doc

redirects.txt
This reverts commit b9897db04f68c1775c1e0955c2ec60d90b6ab812.
=> Revert "[FIX] redirects: add redirection to sales/send_quotations/optional_products"

marketing_automation/overview/segment.rst
=> [ADD] marketing automation: add tags doc on seealso

email_marketing/overview/send_emails.rst, sms_marketing/overview/integrations_and_template.rst
=> [IMP] sms and email marketing: note about doc campaigns

email_marketing/overview/mailing_lists.rst, email_marketing/overview/manage_unsubscriptions.rst, email_marketing/overview/send_emails.rst
Reviewed content to remove not necessary future tenses.
To be merged.
=> [IMP] email marketing: remove future tense

helpdesk/advanced/after_sales.rst, helpdesk/advanced/close_tickets.rst, helpdesk/timesheet_and_invoice/invoice_time.rst, helpdesk/timesheet_and_invoice/reinvoice_from_project.rst
Added FSM doc on see also in after_sales.rst + removed future tense on last added docs.
@AntoineVDV would please merge this doc for me? (:
Thank you!
=> [IMP] helpdesk: add doc on seealso + removed future tense

ecommerce/shopper_experience/paypal.rst
Reflect actual Paypal backend.
=> [FIX] ecommerce,paypal: update `Merchant ID` info

project/tasks/get_started.rst
Added seealso about tags in tasks/get_started.rst.
=> [IMP] project: add doc on seealso

helpdesk/timesheet_and_invoice/reinvoice_from_project.rst
Changed title of reinvoice_from_project.rst
@Lau-Odoo could you please just review this quick change for me, so I can merge it? Merci!
=> [IMP] helpdesk: improved title of reinvoice_from_project.rst

helpdesk/overview.rst
[FIX] helpdesk: fixed toctree overview.rst
=> [FIX] helpdesk: fixed toctree overview.rst

helpdesk/overview/receiving_tickets.rst, helpdesk/overview/sla.rst
Add docs (seealso) on receiving_tickets.rst + sla.rst
@Lau-Odoo would you please approve this PR for me, so I can merge it? Merciiiiiiiii (:
=> [IMP] helpdesk: add docs (seealso) on receiving_tickets.rst + sla.rst

odoo_sh/advanced/submodules.rst
Move an important paragraph at section beginning and emphasize it with a Warning.
OPW-2235054
=> [IMP] odoo_sh: emphasize private submodule must be added using git

studio/concepts/understanding_automated_actions.rst
Fix relative path to doc email_template.rst (discuss) in understanding_automated_actions.rst
=> [IMP] studio: fix relative path to doc

general/multi_companies/manage_multi_companies.rst, general/odoo_basics/add_user.rst
- Included Fiscal Positions + Journal links under Inter-Company Transactions title + remove note about it
- Include doc Multi-Company Guidelines on seealso
- Include manage_multi_companies.rst on seealso in add_user.rst
=> [IMP] general: manage_multi_companies.rst doc improved

survey/overview/time_random.rst
@Lau-Odoo could you please approve this PR for me?
Merci beaucoup! :)
=> [FIX] surveys: fix typo on time_random.rst

planning/overview/send_planned_shifts.rst
@Lau-Odoo Hello! Could you please approve this PR for me? thank you :)
=> [IMP] planning: send_planned_shifts.rst fix typo

social_marketing/overview/campaigns.rst
@jcs-odoo Could you please approve this PR for me? Thank you very much!
=> [IMP] social marketing: fix typo + remove future tense in campaigns.rst

crm/acquire_leads/lead_mining.rst, discuss/overview/plan_activities.rst
Fixes for Odoo 13.0 documentation:
https://www.odoo.com/documentation/user/13.0/crm/acquire_leads/lead_mining.html
=> [FIX] crm: doc fixes for Odoo 13.0

discuss/advanced/email_servers.rst
@jcs-odoo Could you, please, approve this PR? Merci!
=> [FIX] discuss: couple of grammar points fixed

accounting/fiscal_localizations/localizations/chile.rst
The original PR #745 had errors that led to error messages.
Please forward port in 14.0 as well
=> [FIX] accounting: fix bad indenting in chile localization

odoo_sh/getting_started/branches.rst, odoo_sh/getting_started/settings.rst
- test tags have been added
- modules settings have been moved from global settings to branch
settings
=> [IMP] odoo_sh: branch settings

accounting/others/adviser/budget.rst
Correction of obvious mistake.
=> [FIX] Correction of note in budget.rst

crm/optimize/outlook_extension.rst
- Fix of a typo in the text
- Removal of this redirection, since the right link is being updated in Odoo
- crm/optimize/mail_client_extension.rst crm/optimize/outlook_extension.rst
=> [FIX] CRM: typo correction in Outlook Extension doc

db_management/hosting_changes.rst, odoo_sh/getting_started/branches.rst, odoo_sh/getting_started/create.rst, practical.rst, support/supported_versions.rst
=> [IMP] practical/db_management: hosting changes

accounting/overview/main_concepts/in_odoo.rst
=> [IMP] accounting: fix typo in in_odoo.rst

accounting/payables/pay/sepa.rst
=> Update SEPA pain version depending on country

fsm/helpdesk/plan_onsite.rst
"intervention" in the first sentence should be singular :)
=> [FIX] Field Service: fix a typo on the helpdesk tickets page

sms_marketing/pricing/pricing_and_faq.rst
Question about using 'own sms provider' added to the list of frequently asked questions, because it is a common one asked to the product owner.
=> [IMP] sms marketing: update princing_and_faq.rst

accounting/fiscal_localizations/localizations/germany.rst, legal.rst
- add a new section about GoBD compliance in Localizations/Germany
- add a reference link about this section on the legal page
=> [IMP] accounting/loc: add GoBD section to loc/germany

portal/my_odoo_portal.rst
Port of commit 156410173e27dc140b028aaf8997ba04fc8715d0
from PR #862
=> [FIX] portal: remove wrong information and add a link in my portal

inventory/shipping/setup/dhl_credentials.rst
As requested by DHL
OPW-2469052
=> [FIX] shipping/dhl: remove test creds from website

discuss/advanced/email_servers.rst
Added section about how to set up different dedicated servers for transactional and mass mails.
Original PR: #682
=> [IMP] discuss: document dedicated servers setup

general/multi_companies/manage_multi_companies.rst
Added information on note about the requirements for a product to be shared on a multi company environment.
=> [IMP] general: product share between companies

accounting/fiscal_localizations/localizations/peru.rst
The detail to register Digiflow as PSE was missing, with this change the instructons will completed.
=> [IMP] l10n_pe: Improve configuration instructions.rst

accounting/bank/setup/bank_accounts.rst, accounting/overview/getting_started/setup.rst, accounting/receivables/customer_invoices/payment_terms.rst, crm/optimize/outlook_extension.rst
3 out of 4 files could also be changed in 13.0 but it's not important as it is a minor change.
=> [IMP] user-doc: rename "odoo learn" links as "odoo tutorials"

content/applications/finance/accounting/fiscal_localizations/localizations/argentina.rst
Add a link to the latest webinar for ARG related to eCommerce
=> [IMP] l10n_ar: Add eCommerce Webinar

content/applications/finance/accounting/fiscal_localizations/localizations/peru.rst
Update important explanation on Peruvian localization configuration process.
=> [IMP] Accounting: Update Peruvian localization

extensions/odoo_theme/static/style.scss
I don't need to justify anything!
=> hide toctree-wrapper

extensions/odoo_theme/layout_templates/homepage.html, extensions/odoo_theme/static/style.scss
Homepage was too crowded. Removed all the unnecessary images but kept the banner so it looks more like a homepage and not just an index.
=> remove images from homepage

content/applications/productivity/discuss/email_servers.rst
- Document changes from https://github.com/odoo/odoo/pull/69218.
- Explain that Office365 is now usable.
@Tecnativa TT29842
=> [FIX] mail: how to choose allowed "From" addresses

content/developer/reference/javascript_reference.rst
=> [IMP] web, *: clean up notification API

content/developer/reference/views.rst
new option: disable_drag_drop
https://github.com/odoo/odoo/pull/70936
https://github.com/odoo/enterprise/pull/18366
Taskid: 2412172
=> [IMP] developer/reference: add a gantt view option

content/applications/websites/website/publish/translate.rst
https://github.com/odoo/odoo/pull/58678#issuecomment-700627182
=> Gengo was not ported in v14

extensions/odoo_theme/static/style.scss
aligning chevrons, category icons and hrefs
=> [IMP] odoo_theme: padding fix in sidenav

content/applications/finance/accounting/fiscal_localizations/localizations/chile.rst
Add important explanation about Tax on Invoice lines.
=>  [IMP] Accounting: Update Chilean localization

content/developer/reference/data.rst
https://www.odoo.com/documentation/14.0/developer/reference/data.html#csv-data-files
=> [FIX] dev: respect Australian independency

content/developer/howtos/rdtraining/E_unittest.rst, content/developer/reference/cmdline.rst
=> cmdline: clarify --test-tags

content/applications/sales/sales/invoicing/expense.rst
Fixed a couple of english grammar mistakes in the introduction paragraph.
Fixed can be fast-forwaded to 13 and 14 as well.
=> [IMP] sales: fix typos

content/contributing/documentation/content_guidelines.rst, content/contributing/documentation/rst_cheat_sheet.rst
=> [IMP] contributing: refresh doc for new layout and content structure

content/contributing/documentation/rst_cheat_sheet.rst
@AntoineVDV this link changed in 13.0
=> [FIX] contributing: wrong doc reference to "memento"

content/applications/finance/accounting/fiscal_localizations/localizations/chile.rst
Fixed a couple of English grammar mistakes in the invoice PDF report paragraph.
=>  [IMP] l10n_cl : fix typos

content/administration/odoo_sh/getting_started/create.rst
task
https://www.odoo.com/web#id=2581302&action=333&active_id=3835&model=project.task&view_type=form&cids=1&menu_id=4720
=> [IMP] admin/odoo.sh: supported versions in "getting_started/create"

content/applications/finance/accounting/fiscal_localizations/localizations/germany.rst
small addition request by @trj-odoo
=> [IMP] accounting/l10n: add tip about fisaly registration in "germany"

content/applications/sales/sales/amazon_connector/manage.rst
Doc PR: https://github.com/odoo/documentation/pull/1059
Community PR: https://github.com/odoo/odoo/pull/72931
Enterprise PR: https://github.com/odoo/enterprise/pull/19065
task-2573260
=> [IMP] amazon_connector: add a note about the new amazon delivery policy

content/applications/finance/accounting/bank/reconciliation/use_cases.rst
task-2605395
https://www.odoo.com/web#id=2605395&action=333&active_id=3835&model=project.task&view_type=form&cids=1&menu_id=4720
=> [IMP] accounting: remove deprecated tip in "reconciliation/use_cases"

content/applications/finance/accounting/fiscal_localizations/localizations/chile.rst
If the user is hosted in Odoo SH or On-Premise, he should manually install a library and this document will help the support team to easily refer the users on how to do it.
=> [IMP] l10n_cl: Add library needed to print the PDF report

content/developer/reference/frontend/fields.rst
This commits adds the doc regarding those fields:
- EmailField
- PercentageField
- PhoneField
- UrlField
=> [WIP] Adding documentation for fields

content/developer/reference/frontend/fields.rst
This commit adds the following documentation:
- ProgressBarField
=> [WIP] developer: adding fields documentation

content/administration/on_premise/source.rst
Fix small typo introduced in #9116
=> [FIX] fix typo in warning message
