odoo/documentation

- _extensions/odoo/static/mixins.less
Bootstrap forces the img-responsive images to be a block.
IMHO bootstrap should be killed and burned with fire but them it appears I know
nothing (John Snow) about CSS and making things looks nice so they have probably
their reason to do so.
Anyway, not that I care, let me use inline images for Flupke sake!
Before (:-1: :cry:)
After (:+1: :tada:  )
> [FIX] css: rendering of inline images

- general.rst
Without this, unsplash would not be listed in General in the doc
> [FIX] general: add unsplash in toctree

- general/unsplash/unsplash_access_key.rst
- general/unsplash/unsplash_application_id.rst
Unsplash CEO asked us to stop exposing our key client side (even if it was
only in the browser network and allowed by Unsplash API team leader).
Also, all our Odoo instance, on premise or not should share the same
production key, which is not possible for us obviously.
After multiple exchange, it has been negociated that:
1. Our non saas user won't be able to apply for a production key and should
prefix they Unsplash application name by 'Odoo:'. Their key will remain in
test mode.
Indeed, Unsplash won't be able to review every Odoo application and ensure
it respects the API terms and it is a real application.
2. Our saas user will query Unsplash server side so the key remain hidden.
3. The documentation should explain it all
> [IMP] unsplash: new guidelines negociated with Unsplash

- accounting/localizations/mexico.rst
In the mexican documentation we have an errror like the one shown bellow: 
([UNKNOWN NODE title_reference])
In order to make those errors disappear and that the correct information is displayed, what this PR do, is change some special characters.
> [FIX] accounting: Fix mexican view due to a mistake with special characters

- point_of_sale/overview/setup.rst
The tutorial was still describing the installation of a v10 odoo
instance. This pr describes the installation using odoo v11+ and python
3.
related issue:
https://www.odoo.com/web#id=1987423&action=333&active_id=49&model=project.task&view_type=form&menu_id=4720
> [FIX] point_of_sale: POSBoxless

- odoo_sh/getting_started/create.rst
On page https://www.odoo.sh/faq#internet_access we mentions that ports 465 and 587 are open.
We need to align the getting_started page as well.
> Wrong information regarding open ports in outgoing email servers

- ecommerce/shopper_experience/paypal.rst
Mention EWP_SETTINGS error and documentation on docs. (was https://github.com/odoo/documentation-user/pull/277)
> Paypal ewp

- _extensions/odoo/translator.py
- support/supported_versions.rst
While red is supported by most OS as in the unicode version 6 (~2010)
https://dict.emojiall.com/en/emoji/%F0%9F%94%B4
the green and orange circles are very recent so only modern system (by
the way I use Arch) can render it
https://dict.emojiall.com/en/emoji/%F0%9F%9F%A2
Add a patch to be able to use `width` attribute on images
> [IMP] support: display images instead of unicode

- sales/sale_amazon/manage.rst
As of https://github.com/odoo/enterprise/pull/6813 order cancellations from Odoo are no longer notified to Amazon.
> [REM] sale_amazon: removed order cancellation sync from odoo

- accounting/overview/main_concepts/in_odoo.rst
There was a mention that Odoo supports Storno accounting since v9.0.
It is not true and this change must be forward ported on all branches.
Thanks
> [REM] Removal of mention of Storno accounting

- conf.py
Keep the language in multilang versions of pages. The canonical should look like:
- /documentation/user/12.0/sale.html -> /documentation/user/13.0/sale.html
- /documentation/user/11.0/fr/website.html -> /documentation/user/13.0/fr/website.html
Needs the changes at odoo/saas-automation#40 that will change the `canonical_root` from `https://www.odoo.com/documentation/user/` to `https://www.odoo.com/documentation/user/12.0/`
This way, the language switcher will keep the current version, changing from English to French on `/documentation/user/12.0/website.html` will lead to `/documentation/user/12.0/fr/website.html`, not `/documentation/user/13.0/website.html` as before
> [IMP] documentation: make the multiversion, multilang work

- inventory/management/products/uom.rst
The statement:
"When doing a replenishment via the Replenish button on the product form, you have the possibility to change the unit of measure."
Implies that when a replenishment is done the purchase uom will be changed when actually it just creates a stock.move with a calculated amount based on the product's uom.
> Inventory replenishment doesn't change the uom

- inventory/management/replenishment_strategies/min_stock_rule_vs_mto.rst
> MTO doesn't check for the quantity on hand

- _extensions/odoo/translator.py
Merged cells in the first columns were not rendered correctly and values from
other columns would be placed in the wrong columns.
6698bff6 moved in this PR from #554 to handle this starting from 11.0
> [FIX] rendering of tables with merged cells

- sales/invoicing/subscriptions.rst
- sales/send_quotations/terms_and_conditions.rst
Change **Go to SALES ‣ Configuration ‣ Settings and activate Default Terms & Conditions.** to **Go to Accounting ‣ Settings and activate Default Terms & Conditions** This is due to the fact that in V13 the Default Terms & Conditions setting is no longer available in under Sales but rather Accounting in the General Settings as well.
> Update path to default terms and conditions from Sales to Accounting within documentation.

- sales/invoicing/time_materials.rst
Change *Invoicing --> Configuration --> Settings` and activate *Analytic Accounting*.** to **:`Accounting --> Configuration --> Settings` and activate *Analytic Accounting.** This is due to the fact that in V13 the Analytic Accounting setting is no longer available in under but rather Accounting in the General Settings as well.
> update time_materials.rst to reflect correct path to Analytic Accounting in settings. 

- email_marketing/overview/manage_unsubscriptions.rst
A lot of customer are writing ticket with this issue:
When sending a TEST mail marketing from a campaign, they received a
403 error - Access Denied.
It's happening because the res_id is equal 0 and _valid_unsubscribe_token
from mass mailing controller is expecting it to be <> 0.
The res_id is given by the recipient dropdown of the mass mailing campaign
that allows Odoo to match a known record.
opw-2202026
> [FIX] Unsubscribe button 403 reason explanation

- redirects.txt
This commit adds redirections to files moved in odoo/documentation-user#524 (13.0):
- sales/sale_amazon.rst moved to sales/amazon_connector.rst
- sales/sale_amazon/apply.rst moved to sales/amazon_connector/apply.rst
- sales/sale_amazon/setup.rst moved to sales/amazon_connector/setup.rst
- sales/sale_amazon/manage.rst moved to sales/amazon_connector/manage.rst
- sales/sale_ebay.rst moved to sales/ebay_connector.rst
- sales/ebay/setup.rst moved to sales/ebay_connector/setup.rst
- sales/ebay/manage.rst moved to sales/ebay_connector/manage.rst
> [FIX] redirects: add redirections to {amazon,ebay}_connector

- redirects.txt
This commit adds a redirection for files removed in b109c3af (12.0)
following #544 (11.0):
- support/user_doc.rst replaced by contributing/documentation/introduction_guide.rst
> [FIX] redirects: add a redirection to contributing

- project/advanced/advanced_projects.rst
Replaced a :menuselection: by a relative file path to general/developer_mode/activate in advanced_projects.rst.
@AntoineVDV Please, do me the favor of merging this one as well :D Merci beaucoup!!
> [IMP] project: add link to the developer mode doc

- redirects.txt
Accounting redirect
localizations --> fiscal_localizations/localizations
> [FIX] accounting: missing redirect for a mid-menu page

- accounting/fiscal_localizations/localizations/mexico.rst
Updated path reference to certificate & certificate key in order to account for updated path hierarchy of accounting localization documentation changes made for v13 #649
> [FIX] Corrected link to l10n_mx certificate & certificate key in 13.0

- accounting.rst
- applications.rst
This PR has two commits
- [IMP] documentation: reorder the main apps' list
- Reorders the list as requested by @AntoineVDV and defined by the marketing team.
- [REF] doc: modify toctrees for expenses and mobile to unify it with the rest of the doc
- is merely a suggestion to have the same toctree even for apps that currently have only one doc.
- redirects `expense/expense` to `expenses/expenses`
> 13.0-documentation-applications-order-jcs

- odoo_sh/getting_started/branches.rst
Some users have reported that current wording sets the
expectation that there will be a notification when dev
branches will be eliminated after the three days.
This makes it clear that after three days dev branches are
automatically garbage collected at any moment without
prior notice.
> [IMP] odoo_sh: clarify dev branch behavior

- discuss/email_servers.rst
Port 25 is blocked for db hosted on Google Cloud, which mean almost every db on 12.3 & 13.
> [ADD] mailing: port 25 blocked for SMTP

- redirects.txt
The redirection discuss/mail_twitter.rst discuss/overview/get_started.rst # was deleted.
> [IMP] discuss: delete redirection for mail_twitter.rst

- expense/expense.rst
As commited here: 
https://github.com/odoo/odoo/commit/4ba8f51d87be394988e6e2889cf03f351afea1a0
The reference must be in first position in the email subject.
https://github.com/odoo/odoo/blob/13.0/addons/hr_expense/models/hr_expense.py#L568
opw:2255175
> [FIX] expense: Reference in first position in email subject

- _extensions/odoo/layout.html
- _extensions/odoo/translator.py
```rst
.. meta::
:description: blah blah blah
:keywords lang=en: x y z
```
will generate
```html
<meta name="description" content="blah blah blah">
<meta name="keywords" lang="en" content="x y z">
```
Also cleaned up `layout.html` a tad while at it:
* we're now properly setting the default metas via the translator so setting them in the template is unnecessary
* toggle the `html5_doctype` Sphinx flag as it... uses an HTML5 doctype so we don't need to do that by hand anymore (also uses a `charset` meta instead of an `http-equiv="Content-Type"` and suppresses sphinx's own `X-UA-Compatible`)
> [ADD] support for meta directive

- odoo_sh/advanced/submodules.rst
Correct anchor is "_pulling_in_upstream_changes_from_the_submodule_remote" instead of "_pulling_in_upstream_changes"
> [FIX] odoo_sh: wrong anchor link in update submodules part

- general/payment_acquirers/authorize.rst
For Authorize.net configuration, you need individual Receipt and Relay Response URL's.  The previous version featured the same URL twice.  The Relay Response URL here has been updated to reflect proper configuration.
> [FIX] Payment_authorize, Fix relay response URL

- odoo_sh/getting_started/first_module.rst
`api.multi` was removed in 13.0 and is the default behavior. Attempting
to use it in this tutorial will result in a build error.
> [FIX] Remove api.multi which doesn't exist in 13.0

- sales/amazon_connector/features.rst
- sales/amazon_connector/setup.rst
As not all Amazon marketplaces are natively supported, and because new
ones are regularly added by Amazon, this commit adds an exhaustive list
of supported marketplaces.
It also makes a few changes to the guide for adding an unsupported
marketplace in order to point the difference between an unsupported
and an incompatible marketplace.
task-2330255
> [IMP] amazon_connector: list supported marketplaces

- accounting/others/multicurrencies/exchange.rst
- accounting/others/multicurrencies/full_reconcile_warning.rst
- accounting/others/multicurrencies/how_it_works.rst
- accounting/others/multicurrencies/invoices_payments.rst
It's not really obvious that payments and invoices need to be fully
reconciled before their currency exchange entries get created, so this
is a warning about that.
> [IMP] accounting: Warning about currency exchange entries

- odoo_sh/getting_started/branches.rst
It was not clear enough whether or not a backup was triggered when doing code updates.
opw-2341980
> Update backup policy before merge

- timesheets/overview/get_started.rst
Under the title 'Choose an enconding unit', a piece of information was added explaining that the minimal duration and rounding minutes are applied to times added when using the timer, clarifying that it does not apply for manual entries.
> [IMP] timesheets: get_started.rst

- accounting/fiscal_localizations/localizations/chile.rst
l10n_cl (Chile):
The change is due to a request to add webinars we had per localization to improve the visibility of this as a tool both for customers and Odooers. Why at the beginning? This is because is the first thing you see when accessing the documentation.
This is a minor change.
> [IMP] localization: add "webinars" section to Chile

- accounting/fiscal_localizations/localizations/argentina.rst
- accounting/fiscal_localizations/localizations/colombia.rst
l10n_co (Colombia):
The change is due to a request to add webinars we had per localization to improve the visibility of this as a tool both for customers and Odooers. Why at the beginning? This is because is the first thing you see when accessing the documentation.
This is a minor change.
> [IMP] localization: add "webinars" section to Argentina and Colombia

- accounting/localizations/mexico.rst
A Mexican company should keep MXN as default company. This is actually a
legal obligation.
> [IMP] accounting: mexico - MXN as default currency

- db_management/db_upgrade.rst
documentation update as we have removed the `-c` option from
the upgrade script to provide the subscription code. Now
it is directly read from the database.
> [FIX] upgrade: remove the contract parameter

- redirects.txt
With the introduction of V14, all the easy flows to be removed to avoid an
increasing technical debt. For purchase, approximately 2/3 of the pages were
removed, which meant that a reorganisation and simplification of the structure
was necessary. A couple of removed docs now point out to docs under other apps
to avoid duplicating the information.
> [FIX] purchase: create redirects for moved, deleted and merged docs

- purchase/manage_deals/agreements.rst
The info about the "Agreement deadline" was wrong and was removed. A typo was
also fixed.
> [FIX] purchase/agreements: fix a typo and remove a sentence

- contributing/documentation/content_guidelines.rst
As you suggested it, @AntoineVDV , here is an addition about media filenames in the content guidelines.
> [IMP] guidelines: add media files section in content guidelines

- odoo_sh/advanced/frequent_technical_questions.rst
CUPS the server will never be installed on an Odoo.sh machine.
That being said you can use a remote printer with a cups client.
The problem lays in the sorry state of libcups dependencies so we will
try to get a reliable section in the documentation for 20.04 as soon as
we can get a testcase.
Meanwhile, it has been reported that the command line `lp` cups cli
client tool could be used as a workaround in the OCA concerned module:
https://gist.github.com/rm-jamotion/0453e91ff3e13350a1e46a11ebb02e8d
Reapply of https://github.com/odoo/documentation-user/commit/3b4c795
> [REM] odoo_sh: remove incorrect information about cups

- content/applications/websites/ecommerce/managing_products/stock.rst
As per the documentation, it is possible to show inventory availability under ecommerce without
installing Inventory app which is incorrect. 
Made the appropriate changes.
> [IMP] ecommerce: updated mention about inventory app

- content/administration/install.rst
* Change 13.0 references to 14.0
* Change Ubuntu version to 20.04 as it was the stable version at Odoo
release time
* Remove unnecessary postgresql pre-installation as Debian and Ubuntu
install the recommended packages by default
* Replace `root` commands by `sudo` commands as it's the preferred way
to run admin commands
* Remove the manual installation of xlwt and num2words as the Debian
packages now exist.
* Bump the supported Fedora version to Fedora 32.
* Add a warning about unsupported Fedora 33 (because of Python 3.9 that
would need a separate package)
> [FIX] install: adapt debian and rpm package installation

- content/legal.rst
This avoids to have URL pointing to
`https://www.odoo.com/documentation/user/<VERSION>/<LANG>/odoo_enterprise_agreement.pdf`
when switching a language
The pdf are built only once and are global per version
> [FIX] legal: use direct links to pdf files

- extensions/odoo_theme/layout.html
- extensions/odoo_theme/layout_templates/searchbox.html
- extensions/odoo_theme/static/style.scss
- Remove duplicate search bar used for mobile and improve css so primary search bar can adapt to mobile. 
Avoiding two identical ids in the DOM.
- Position `Hide Search Matches` button next to search bar on desktop, below search bar on mobile.
> Remove duplicate search bar and improve css + fix hide search matches button

- extensions/odoo_theme/layout_templates/homepage.html
According to the app-store guidelines we are not allowed to sell from
the iOS app.
Our updates are currently blocked because of this.
In the rush, we have no choice but to hide "Try Odoo for FREE" buttons
that redirects the customer to the subscription page.
This is unfortunately not allowed by Apple who consider this
as "In-App Purchase".
Note that in the old documentation (https://www.odoo.com/documentation/user),
this button was located in the header which was hidden in the app
(see related PR).
Source: https://developer.apple.com/app-store/review/guidelines/#business
Related PR:
odoo/mobile-ios#102
odoo/mobile-ios#103
Task-id: 2483253
> [FIX] theme: hide "Try Odoo" button on iOS

- redirects.txt
This redirection was seemingly forgotten in the nginx redirections deployed online,
we will cover it through the redirects file then.
> [FIX] redirects: odoo_sh documentation page

- Makefile
- extensions/autodoc_placeholder/__init__.py
- extensions/embedded_video/__init__.py
- extensions/exercise_admonition/__init__.py
- extensions/github_link/__init__.py
- extensions/html_domain/__init__.py
- extensions/odoo_theme/__init__.py
- extensions/redirects/__init__.py
- extensions/switcher/__init__.py
Now that patchqueue was removed, we can consider supporting the parallel 
read with our local extensions.
Since we only have basic extensions, not storing any data on the build 
environment, the change mainly consists of specifying the extensions as 
parallelizable.
The only specific case is the html domain, since the base html domain 
requires the support of the method merge_domaindata in parallel read 
mode.  Since we do not need to share anything between the envs for this 
extension, we can simply ignore the method.
> [FIX] extensions: support parallel read

- content/applications/finance/accounting/fiscal_localizations/localizations/france.rst
- content/applications/finance/accounting/receivables/customer_invoices/overview.rst
Rebase of 825
commit ef4209d2763de607bd44ae937ce7266677bd69f9
The module ' l10n_fr_certification ' has been integrate in the account module.
so this is not installable anymore. Removed this but kept the explanation
for the POS.
commit a98d026bf8cea20410b4a3f074ad25ab48e0e93e
The re sequencing feature done by WAN is perturbing our french customer
In order to explain the reason the feature is, let's state what has been
decided by the product owner (TSB)
opw-2389435
> [REM/ADD] account: remove none relevant module + re sequencing restriction

- content/developer/reference/orm.rst
For SQL parameters `execute` takes a single argument with a list, tuple
or dict, not multiple arguments.
`execute` isn't explicitly documented here, and that might have been on purpose, so I did not expand further on its arguments. That being said, if we were to document it properly, this might be a good spot. Thoughts?
> [FIX] Corrected cr.execute example

- extensions/odoo_theme/__init__.py
When navigating the themes tutorial (developer/howto/themes), the rdtraining page wasn't clickable
in the global toc, even though it was specified as :show-content: (note that the rdtraining was only added in 14+).
The current heuristic extracting the pagename from a toctree node wasn't considering the current depth
if the page referenced by the toctree node was in the same folder than the current page.
Explanation:
We are computing the toctree for the page developer/howtos/themes.
One of the toctree nodes references the rdtraining page, with a relative link,
i.e. `rdtraining.html`.
We were wrongfully looking for show_content in the metadata of the `rdtraining` page,
instead of `developer/howtos/rdtraining`, since we didn't consider the current document
depth when the reference didn't …
> [FIX] odoo_theme: unclickable :show-content: pages in global toctree

- content/developer/howtos/rdtraining/16_guidelines_pr.rst
no need to fetch all branches from odoo/technical-training-sandbox
Also, ``git push`` without upstream may not work depending on git
version/configuration:
```
$ git push -u master-my_first_branch-IEL
fatal: The current branch master-my_first_branch-IEL has no upstream branch.
To push the current branch and set the remote as upstream, use
git push --set-upstream master-my_first_branch-IEL master-my_first_branch-IEL
```
> [FIX] rdtraining: improve git commands

- content/developer/reference/orm.rst
Since Odoo 12: https://github.com/odoo/odoo/commit/52a8ed3c0c72b21baf589bc9b91a030d9da661a8
Also this adds a note about `copy` attribute.
> [FIX] orm: readonly is True for related fields.

- extensions/odoo_theme/static/js/menu.js
- extensions/odoo_theme/static/style.scss
On mobile, the searchbar is fixed and overlays the content because its parent (header) is fixed.
In order to not have a duplicate of the searchbar for mobile, I decided the best option was to hide the searchbar on scroll.
Added JS to listen to scroll.
> hide searchbar on scroll

- content/applications/inventory_and_mrp/manufacturing/management/bill_configuration.rst
The destination location in manufacturing order shouldn't be a scrap location. Otherwise the user won't be able to complete manufacturing orders.
> [IMP] manufacturing: add warning regarding scrap location

- extensions/odoo_theme/static/js/menu.js
When a page is referenced multiple times in the global toctree, only its
latest TOC entry was highlighted (and expanded if it's a TOC page).
This commit allows a page to be referenced multiple times at any level
of the global TOC while correctly highlighting all of its TOC entries.
task-2551473
> [FIX] odoo_theme: highlight all occurrences of a same entry in the menu

- content/developer/howtos.rst
- content/developer/howtos/web.rst
Now that the new rd&training is deployed, we shouldn't highlight this page anymore
Fixes #1017
> [IMP] dev/howtos: hide deprecated and outdated tutorial

- content/applications/finance/accounting/fiscal_localizations/localizations/mexico.rst
This is a result of a feedback we've received, in previous MX DOC versions we were specifying that the company/main currency should be MXN.
This is good to have it as a warning, we have as a warning in previous DOV versions but now we add some extra info as well (ref: https://www.odoo.com/documentation/13.0/applications/finance/accounting/fiscal_localizations/localizations/mexico.html#set-your-legal-information-in-the-company)
> [IMP] l10n_mx: Add extra paragraph in Warning (MXN currency)

- content/developer/howtos/rdtraining/03_newapp.rst
`web` is not used directly and is installed automatically anyway.
Having both `web` and `base` looks excessively, so coaches usually ask to delete
`base`. But more correct solution is adding `base` only. Completly skipping
dependencies is not good either -- see 76e05cc
> [IMP] rdtraining: no need to add web to dependencies

- content/developer/reference/views.rst
This commit relates to a new community feature:
A read_group on a date(time) field will also return a __range property with
the date bounds of the group [from, to[
The community commit also introduces a new xml attribute
`allow_group_range_value` for `<kanban>` `<field>`, and this commit is the
documentation for that attribute.
allow_group_range_value (boolean):
- to perform a drag&drop or a quickCreate, we must be able to get and use the
value from the group containing the record. The last date of the group will
be taken as the record's field value.
- allows (or disallows) date(time) non-readonly fields to be:
- draggable
- quick created
- defaults to false.
Task-ID: 2243913
Community PR odoo/odoo#69380  
> Commit: [IMP] core, web: add a range for date(time) read_group
> [IMP] developer/views: document new kanban field attribute

- content/developer/misc/other/guidelines.rst
The 'oldname' tag has been deprecated for a few years
> [IMP] guidelines: remove a deprecated tag

- Makefile
- conf.py
Building documentation implies some constraints: the source folder is
readonly, mainly because the sources are shared accros builds.
This implies that nor a symlink and a _build dir cannot be added in the
source directory.
The symlink will work in most cases localy for user with strange
multiverse structure, but if not found, the fallback will check in
parent directory. Most users and runbot will have all sources in the
same directory (both in universe and basic multiverse cases)
-(version?)
-odoo
-enterprise
-upgrade
-documentation
The second change will check if BUILD_DIR is defined before setting it,
allowing to use 'make BUILD_DIR=../build' to output the documentation
somewhere else.
> [IMP] allow to define BUILD_DIR and better odoo detection

- content/administration/install/deploy.rst
As discussed in #1013, this is the same diff but targeting v14.0 (taking into account the changes in the config, like the `ssl_protocols`.
> [FIX] Indentation in nginx config is now consistent (two spaces)

- content/legal/terms/enterprise.rst
- content/legal/terms/i18n/enterprise_fr.rst
Updated terms for fall 2022 pricing:
- removal of "per app" notion
- addition of "subscription plan" notion
Will be backported later due to some conflicts.
PS: pre-approved by legal team and CEO ;-)
> [CHG] legal: enterprise terms for fall 2022 pricing

- conf.py
https://werkzeug.palletsprojects.com/en/1.0.x/objects.inv now returns a 404.
> [FIX] werkzeug version

- content/applications/hr/payroll/payroll_localizations/united_arab_emirates.rst
Updating doc according to [this task](https://www.odoo.com/odoo/project.task/4941628).
> [IMP] Payroll: Updates to UAE Localization
